params: {}

queries:
  linkflaechen_update_flaechen_makevalid: |
    UPDATE flaechen SET geom = MakeValid(geom)

  linkflaechen_update_tezg_makevalid: |
    UPDATE tezg SET geom = MakeValid(geom)

  linkflaechen_delete_linkfl_glink_null: |
    DELETE FROM linkfl WHERE glink IS NULL

  linkflaechen_delete_linksw_glink_null: |
    DELETE FROM linksw WHERE glink IS NULL

  linkflaechen_delete_linkageb_glink_null: |
    DELETE FROM linkageb WHERE glink IS NULL

  linkflaechen_updatelinkfl_set_flnam: |
    WITH linksvalid AS (
        SELECT lf.pk
        FROM linkfl AS lf
        INNER JOIN flaechen AS fl ON lf.flnam = fl.flnam
        WHERE fl.geom IS NOT NULL AND within(StartPoint(lf.glink), fl.geom)
    )
    UPDATE linkfl SET flnam = (
        SELECT flnam
        FROM flaechen AS fl
        WHERE within(StartPoint(linkfl.glink), fl.geom) AND fl.geom IS NOT NULL
    )
    WHERE linkfl.pk NOT IN linksvalid

  linkflaechen_updatelinkfl_set_haltnam: |
    WITH linksvalid AS (
        SELECT lf.pk
        FROM linkfl AS lf
        INNER JOIN haltungen AS ha ON lf.haltnam = ha.haltnam
        WHERE ha.geom IS NOT NULL AND Distance(EndPoint(lf.glink), ha.geom) < ?
    )
    UPDATE linkfl SET haltnam = (
        SELECT haltnam
        FROM haltungen AS ha
        WHERE Distance(EndPoint(linkfl.glink), ha.geom) < ?
    )
    WHERE linkfl.pk NOT IN linksvalid

  linkflaechen_updatelinkfl_set_tezgnam: |
    WITH linksvalid AS (
        SELECT lf.pk
        FROM linkfl AS lf
        INNER JOIN tezg AS tg ON lf.tezgnam = tg.flnam
        INNER JOIN flaechen AS fl ON lf.flnam = fl.flnam
        WHERE ((fl.aufteilen <> 'ja' AND not fl.aufteilen) OR fl.aufteilen IS NULL)
           OR (tg.geom IS NOT NULL AND within(StartPoint(lf.glink), buffer(tg.geom, ?)))
    )
    UPDATE linkfl SET tezgnam = (
        SELECT flnam
        FROM tezg AS tg
        WHERE within(StartPoint(linkfl.glink), tg.geom)
    )
    WHERE linkfl.pk NOT IN linksvalid

  linkflaechen_updatelinksw_set_elnam: |
    WITH linksvalid AS (
        SELECT lf.pk
        FROM linksw AS lf
        INNER JOIN einleit AS el ON lf.elnam = el.elnam
        WHERE el.geom IS NOT NULL AND Distance(StartPoint(lf.glink), el.geom) < ?
    )
    UPDATE linksw SET elnam = (
        SELECT elnam
        FROM einleit AS el
        WHERE contains(buffer(StartPoint(linksw.glink), ?), el.geom)
    )
    WHERE linksw.pk NOT IN linksvalid

  linkflaechen_updatelinksw_set_haltnam: |
    WITH linksvalid AS (
        SELECT lf.pk
        FROM linksw AS lf
        INNER JOIN haltungen AS ha ON lf.haltnam = ha.haltnam
        WHERE ha.geom IS NOT NULL AND Distance(EndPoint(lf.glink), ha.geom) < ?
    )
    UPDATE linksw SET haltnam = (
        SELECT haltnam
        FROM haltungen AS ha
        WHERE Distance(EndPoint(linksw.glink), ha.geom) < ?
    )
    WHERE linksw.pk NOT IN linksvalid

  linkflaechen_updatelinksw_sync_einleit_haltnam: |
    WITH linksvalid AS (
        SELECT el.pk
        FROM einleit AS el
        INNER JOIN linksw AS lf ON el.elnam = lf.elnam
        WHERE el.haltnam <> lf.haltnam
    )
    UPDATE einleit SET haltnam = (
        SELECT haltnam
        FROM linksw AS lf
        WHERE einleit.elnam = lf.elnam
    )
    WHERE einleit.pk IN linksvalid

  linkflaechen_updatelinkageb_set_gebnam: |
    WITH linksvalid AS (
        SELECT lg.pk
        FROM linkageb AS lg
        LEFT JOIN aussengebiete AS ag ON lg.gebnam = ag.gebnam
        WHERE ag.pk IS NOT NULL AND within(StartPoint(lg.glink), ag.geom)
    )
    UPDATE linkageb SET gebnam = (
        SELECT gebnam
        FROM aussengebiete AS ag
        WHERE within(StartPoint(linkageb.glink), ag.geom)
    )
    WHERE linkageb.pk NOT IN linksvalid

  linkflaechen_updatelinkageb_set_schnam: |
    WITH linksvalid AS (
        SELECT lg.pk
        FROM linkageb AS lg
        LEFT JOIN schaechte AS sc ON lg.schnam = sc.schnam
        WHERE sc.pk IS NOT NULL AND contains(buffer(EndPoint(lg.glink), ?), sc.geom)
    )
    UPDATE linkageb SET schnam = (
        SELECT schnam
        FROM schaechte AS sc
        WHERE contains(buffer(EndPoint(linkageb.glink), ?), sc.geom)
    )
    WHERE linkageb.pk NOT IN linksvalid

  linkflaechen_updatelinkageb_sync_aussengebiete_schnam: |
    WITH linksvalid AS (
        SELECT ag.pk
        FROM aussengebiete AS ag
        INNER JOIN linkageb AS lg ON ag.gebnam = lg.gebnam
        WHERE ag.schnam == lg.schnam
    )
    UPDATE aussengebiete SET schnam = (
        SELECT schnam
        FROM linkageb AS lg
        WHERE aussengebiete.gebnam = lg.gebnam
    )
    WHERE aussengebiete.pk NOT IN linksvalid

  linkflaechen_insert_teilgebiete_from_flaechen: |
    INSERT INTO teilgebiete (tgnam)
    SELECT teilgebiet FROM flaechen
    WHERE teilgebiet IS NOT NULL AND teilgebiet <> ''
      AND teilgebiet NOT IN (SELECT tgnam FROM teilgebiete)
    GROUP BY teilgebiet

  linkflaechen_insert_teilgebiete_from_haltungen: |
    INSERT INTO teilgebiete (tgnam)
    SELECT teilgebiet FROM haltungen
    WHERE teilgebiet IS NOT NULL AND teilgebiet <> ''
      AND teilgebiet NOT IN (SELECT tgnam FROM teilgebiete)
    GROUP BY teilgebiet

  linkflaechen_insert_teilgebiete_from_einleit: |
    INSERT INTO teilgebiete (tgnam)
    SELECT teilgebiet FROM einleit
    WHERE teilgebiet IS NOT NULL AND teilgebiet <> ''
      AND teilgebiet NOT IN (SELECT tgnam FROM teilgebiete)
    GROUP BY teilgebiet

  linkflaechen_select_abflussparameter: |
    SELECT abflussparameter FROM flaechen GROUP BY abflussparameter

  linkflaechen_select_entwart: |
    SELECT "entwart" FROM "haltungen" GROUP BY "entwart"

  linkflaechen_select_tgnam: |
    SELECT "tgnam" FROM "teilgebiete" GROUP BY "tgnam"

  linkflaechen_count_flaechen_ohne_aufteilen: |
    SELECT count(*) AS anzahl FROM flaechen
    WHERE ((aufteilen <> 'ja' AND not aufteilen) OR aufteilen IS NULL){auswahl}

  linkflaechen_count_flaechen_aufteilen_ja: |
    SELECT count(*) AS anzahl FROM flaechen WHERE aufteilen = 'ja' {auswahl}

  linkflaechen_count_haltungen: |
    SELECT count(*) AS anzahl FROM haltungen {auswahl}

  linkflaechen_count_einleit: |
    SELECT count(*) AS anzahl FROM einleit {auswahl}

  linkflaechen_list_group_attributes: |
    SELECT teilgebiet, tabelle, printf('%i', count(*)) AS Anzahl
    FROM gruppen
    WHERE grnam = ?
    GROUP BY tabelle, teilgebiet
    ORDER BY tabelle, teilgebiet

  linkflaechen_select_grnam: |
    SELECT grnam FROM gruppen GROUP BY grnam

  linkflaechen_createlinkfl_insert_mit_tezg: |
    WITH linkadd AS (
        SELECT fl.flnam, fl.teilgebiet, fl.abflussparameter, fl.geom
        FROM flaechen AS fl
        LEFT JOIN linkfl AS lf ON lf.flnam = fl.flnam
        WHERE ((fl.aufteilen <> 'ja' AND not fl.aufteilen) OR fl.aufteilen IS NULL)
          AND lf.pk IS NULL AND area(fl.geom) > {mindestflaeche}{ausw_einf}
    )
    INSERT INTO linkfl (flnam, tezgnam, teilgebiet, geom)
    SELECT la.flnam, tg.flnam AS tezgnam, la.teilgebiet, la.geom
    FROM linkadd AS la
    INNER JOIN tezg AS tg ON within(PointOnSurface(la.geom), tg.geom){ausw_teil}

  linkflaechen_createlinkfl_insert_ohne_tezg: |
    WITH linkadd AS (
        SELECT fl.flnam, fl.teilgebiet, fl.abflussparameter, fl.geom
        FROM flaechen AS fl
        LEFT JOIN linkfl AS lf ON lf.flnam = fl.flnam
        WHERE ((fl.aufteilen <> 'ja' AND not fl.aufteilen) OR fl.aufteilen IS NULL)
          AND lf.pk IS NULL AND area(fl.geom) > {mindestflaeche}{ausw_einf}
    )
    INSERT INTO linkfl (flnam, tezgnam, teilgebiet, geom)
    SELECT la.flnam, NULL AS tezgnam, la.teilgebiet, la.geom
    FROM linkadd AS la

  linkflaechen_createlinkfl_insert_verschneidung: |
    WITH linkadd AS (
        SELECT fl.flnam, tg.flnam AS tezgnam, fl.teilgebiet,
               fl.geom AS geof, tg.geom AS geot
        FROM flaechen AS fl
        INNER JOIN tezg AS tg
          ON intersects(fl.geom, tg.geom) AND fl.geom IS NOT NULL AND tg.geom IS NOT NULL
        LEFT JOIN linkfl AS lf ON lf.flnam = fl.flnam AND lf.tezgnam = tg.flnam
        WHERE (fl.aufteilen = 'ja' OR fl.aufteilen)
          AND lf.pk IS NULL AND area(fl.geom) > {mindestflaeche}{ausw_vers}
    )
    INSERT INTO linkfl (flnam, tezgnam, teilgebiet, geom)
    SELECT la.flnam, la.tezgnam, la.teilgebiet,
           CastToMultiPolygon(CollectionExtract(intersection(la.geof, la.geot), 3)) AS geom
    FROM linkadd AS la
    WHERE geom IS NOT NULL AND area(geom) > {mindestflaeche}

  linkflaechen_createlinkfl_insert_ohne_verschneidung: |
    WITH linkadd AS (
        SELECT linkfl.pk AS lpk, fl.flnam, fl.aufteilen, fl.teilgebiet, fl.geom
        FROM flaechen AS fl
        LEFT JOIN linkfl ON linkfl.flnam = fl.flnam
        WHERE ((fl.aufteilen <> 'ja' OR fl.aufteilen IS NULL)
          AND linkfl.pk IS NULL
          AND fl.geom IS NOT NULL){ausw_einf}
    )
    INSERT INTO linkfl (flnam, teilgebiet, geom)
    SELECT flnam, teilgebiet, geom
    FROM linkadd
    WHERE area(geom) > {mindestflaeche}

  linkflaechen_update_linkfl_gbuf: |
    UPDATE linkfl SET gbuf = CastToMultiPolygon(buffer(geom, ?)) WHERE linkfl.glink IS NULL

  linkflaechen_createlinkfl_update_glink_in_tezg: |
    WITH tlink AS (
        SELECT lf.pk AS pk,
               ha.haltnam,
               Distance(ha.geom, {bezug}) AS dist,
               ha.geom AS geohal,
               lf.geom AS geolf
        FROM (SELECT * FROM haltungen WHERE rwanschluss = 1) AS ha
        INNER JOIN linkfl AS lf ON Intersects(ha.geom, lf.gbuf)
        INNER JOIN tezg AS tg ON tg.flnam = lf.tezgnam
        WHERE (within(centroid(ha.geom), tg.geom) and lf.glink IS NULL
          and ha.geom IS NOT NULL and lf.gbuf IS NOT NULL and tg.geom IS NOT NULL){auswha}
    )
    UPDATE linkfl SET (glink, haltnam) = (
        SELECT MakeLine(PointOnSurface(Buffer(t1.geolf, -1.1*{fangradius})), Centroid(t1.geohal)), t1.haltnam
        FROM tlink AS t1
        INNER JOIN (SELECT pk, Min(dist) AS dmin FROM tlink GROUP BY pk) AS t2
          ON t1.pk = t2.pk AND t1.dist <= t2.dmin + 0.000001
        WHERE linkfl.pk = t1.pk AND area(Buffer(t1.geolf, -1.1*{fangradius})) IS NOT NULL
    )
    WHERE linkfl.glink IS NULL {auswlinkfl}

  linkflaechen_createlinkfl_update_glink: |
    WITH tlink AS (
        SELECT lf.pk AS pk,
               ha.haltnam,
               Distance(ha.geom, {bezug}) AS dist,
               ha.geom AS geohal,
               lf.geom AS geolf
        FROM (SELECT * FROM haltungen WHERE rwanschluss = 1) AS ha
        INNER JOIN linkfl AS lf ON Intersects(ha.geom, lf.gbuf)
        WHERE lf.glink IS NULL and ha.geom IS NOT NULL and lf.gbuf IS NOT NULL {auswha}
    )
    UPDATE linkfl SET (glink, haltnam) = (
        SELECT MakeLine(PointOnSurface(Buffer(t1.geolf, -1.1*{fangradius})), Centroid(t1.geohal)), t1.haltnam
        FROM tlink AS t1
        INNER JOIN (SELECT pk, Min(dist) AS dmin FROM tlink GROUP BY pk) AS t2
          ON t1.pk = t2.pk AND t1.dist <= t2.dmin + 0.000001
        WHERE linkfl.pk = t1.pk AND area(Buffer(t1.geolf, -1.1*{fangradius})) IS NOT NULL
    )
    WHERE linkfl.glink IS NULL {auswlinkfl}

  linkflaechen_createlinksw_insert: |
    INSERT INTO linksw (elnam, teilgebiet, geom)
    SELECT einleit.elnam, einleit.teilgebiet, buffer(einleit.geom, 0.5)
    FROM einleit
    LEFT JOIN linksw ON linksw.elnam = einleit.elnam
    WHERE linksw.pk IS NULL {auswahl}

  linkflaechen_update_linksw_gbuf: |
    UPDATE linksw SET gbuf = CastToMultiPolygon(buffer(geom, ?)) WHERE linksw.glink IS NULL

  linkflaechen_createlinksw_update_glink: |
    WITH tlink AS (
        SELECT sw.pk AS pk,
               Distance(hal.geom, sw.geom) AS dist,
               hal.geom AS geohal,
               sw.geom AS geosw
        FROM (SELECT * FROM haltungen WHERE rwanschluss = 1) AS hal
        INNER JOIN linksw AS sw ON Intersects(hal.geom, sw.gbuf)
        WHERE sw.glink IS NULL AND hal.ROWID IN (
            SELECT ROWID FROM SpatialIndex
            WHERE f_table_name = 'haltungen' AND search_frame = sw.gbuf
        ) and hal.geom IS NOT NULL and sw.gbuf IS NOT NULL {auswahl}
    )
    UPDATE linksw SET glink = (
        SELECT MakeLine(PointOnSurface(t1.geosw), Centroid(t1.geohal))
        FROM tlink AS t1
        INNER JOIN (SELECT pk, Min(dist) AS dmin FROM tlink GROUP BY pk) AS t2
          ON t1.pk = t2.pk AND t1.dist <= t2.dmin + 0.000001
        WHERE linksw.pk = t1.pk
    )
    WHERE linksw.glink IS NULL {auswlin}

  linkflaechen_assigntgeb_within_no_buffer: |
    UPDATE {table} SET teilgebiet = (
        SELECT teilgebiete.tgnam
        FROM teilgebiete
        INNER JOIN {table} AS tt ON within(tt.{geom}, teilgebiete.geom)
        WHERE tt.pk = {table}.pk
          and tt.{geom} IS NOT NULL and teilgebiete.geom IS NOT NULL {auswahl_1}
    )
    WHERE {table}.pk IN (
        SELECT {table}.pk
        FROM teilgebiete
        INNER JOIN {table} ON within({table}.{geom}, teilgebiete.geom)
        WHERE {table}.{geom} IS NOT NULL and teilgebiete.geom IS NOT NULL {auswahl_1}
    )

  linkflaechen_assigntgeb_within_buffer: |
    UPDATE {table} SET teilgebiet = (
        SELECT teilgebiete.tgnam
        FROM teilgebiete
        INNER JOIN {table} AS tt ON within(tt.{geom}, buffer(teilgebiete.geom, {bufferradius}))
        WHERE tt.pk = {table}.pk
          and tt.{geom} IS NOT NULL and teilgebiete.geom IS NOT NULL{auswahl_1}
    )
    WHERE {table}.pk IN (
        SELECT {table}.pk
        FROM teilgebiete
        INNER JOIN {table} ON within({table}.{geom}, buffer(teilgebiete.geom, {bufferradius}))
        WHERE {table}.{geom} IS NOT NULL and teilgebiete.geom IS NOT NULL{auswahl_1}
    )

  linkflaechen_assigntgeb_overlaps: |
    UPDATE {table} SET teilgebiet = (
        SELECT teilgebiete.tgnam
        FROM teilgebiete
        INNER JOIN {table} AS tt ON intersects(tt.{geom}, teilgebiete.geom)
        WHERE tt.pk = {table}.pk
          and tt.{geom} IS NOT NULL and teilgebiete.geom IS NOT NULL{auswahl_1}
    )
    WHERE {table}.pk IN (
        SELECT {table}.pk
        FROM teilgebiete
        INNER JOIN {table} ON intersects({table}.{geom}, teilgebiete.geom)
        WHERE {table}.{geom} IS NOT NULL and teilgebiete.geom IS NOT NULL{auswahl_1}
    )

  linkflaechen_reload_group_table: |
    UPDATE {table}
    SET teilgebiet = (
        SELECT g.teilgebiet
        FROM gruppen AS g
        WHERE g.grnam = '{gruppenname}'
          AND g.tabelle = '{table}'
          AND {table}.pk = g.pktab
    )
    WHERE {table}.pk IN (
        SELECT g.teilgebiet
        FROM gruppen AS g
        WHERE g.grnam = '{gruppenname}'
          AND g.tabelle = '{table}'
    )

  linkflaechen_store_group_base: |
    INSERT INTO gruppen (grnam, pktab, teilgebiet, tabelle, kommentar)
    SELECT
        '{gruppenname}' AS grnam,
        pk AS pktab,
        teilgebiet AS teilgebiet,
        'haltungen' AS tabelle,
        '{kommentar}' AS kommentar
    FROM haltungen
    WHERE teilgebiet <> '' And teilgebiet IS NOT NULL

  linkflaechen_store_group_union_part: |
    UNION
    SELECT
        '{gruppenname}' AS grnam,
        pk AS pktab,
        teilgebiet AS teilgebiet,
        '{table}' AS tabelle,
        '{kommentar}' AS kommentar
    FROM {table}
    WHERE teilgebiet <> '' And teilgebiet IS NOT NULL
