params:
  x_func: x
  y_func: y
  area_func: area
  intersects_func: Intersects
queries:
  linkflaechen_k_link_213: |-
    WITH linkadd AS (
            # SELECT
            # linkfl.pk AS lpk, tezg.flnam AS tezgnam, flaechen.flnam,
            # flaechen.geom
            # FROM flaechen
            # INNER JOIN tezg
            # ON within(centroid(flaechen.geom),tezg.geom)
            # LEFT JOIN linkfl
            # ON linkfl.flnam = flaechen.flnam
            # WHERE ((flaechen.aufteilen <> 'ja' OR flaechen.aufteilen IS NULL)
            # and flaechen.geom IS NOT NULL and tezg.geom IS NOT NULL){ausw_einf}
            # UNION
            # SELECT
            # linkfl.pk AS lpk, tezg.flnam AS tezgnam, flaechen.flnam,
            # CastToMultiPolygon(CollectionExtract(intersection(flaechen.geom,tezg.geom),3)) AS geom
            # FROM flaechen
            # INNER JOIN tezg
            # ON intersects(flaechen.geom,tezg.geom)
            # LEFT JOIN linkfl
            # ON linkfl.flnam = flaechen.flnam AND linkfl.tezgnam = tezg.flnam
            # WHERE (flaechen.aufteilen = 'ja'
            # and flaechen.geom IS NOT NULL and tezg.geom IS NOT NULL){ausw_teil})
            # INSERT INTO linkfl (flnam, tezgnam, geom)
            # SELECT flnam, tezgnam, geom
            # FROM linkadd
            # WHERE lpk IS NULL AND area(geom) > {minfl}